version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/civitechglobal-server"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/civitechglobal-web"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/civitechglobal-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/civitechglobal-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
