import type { ProductDef } from '../types.js';
import { area, claimHistory, currencyField, peopleCount, unitCount } from '../fields.js';

const LIABILITY_LIMITS = [
  { value: 'diyeh-1', label: 'یک دیه کامل', labelEn: 'One full blood-money unit' },
  { value: 'diyeh-2', label: 'دو دیه کامل', labelEn: 'Two full units' },
  { value: 'diyeh-3', label: 'سه دیه کامل', labelEn: 'Three full units' },
  { value: 'custom', label: 'سقف دلخواه — با کارشناس هماهنگ می‌شود', labelEn: 'Custom — agreed with a specialist' },
];

export const liabilityProducts: ProductDef[] = [
  {
    slug: 'liability-medical',
    categorySlug: 'liability',
    title: 'مسئولیت حرفه‌ای پزشکان و پیراپزشکان',
    titleEn: 'Medical professional liability',
    summary: 'پوشش قصور حرفه‌ای در ارائه خدمات درمانی',
    summaryEn: 'Covers professional negligence in delivering care',
    description:
      'بیمه مسئولیت پزشکان، پزشک را در برابر خسارت‌های مالی و جانی ناشی از قصور، خطا یا غفلت حرفه‌ای در جریان ارائه خدمات درمانی پوشش می‌دهد. حق بیمه به شدت به رشته تخصصی و سقف تعهدات انتخابی بستگی دارد، چون ریسک رشته‌های مختلف بسیار متفاوت است. تعهد بیمه‌گر تا چهار سال پس از پایان بیمه‌نامه نیز ادامه دارد.',
    descriptionEn:
      'Medical liability covers a clinician against financial and bodily-injury claims arising from professional negligence, error or omission while treating patients. The premium varies sharply by specialty and chosen limit, because risk differs enormously between disciplines. The insurer’s obligation extends four years beyond the policy’s expiry.',
    coverages: ['دیه فوت', 'دیه نقص عضو', 'هزینه‌های پزشکی بیمار'],
    notes: [
      'اعلام خسارت باید ظرف ۵ روز کاری انجام شود.',
      'تعهد بیمه‌گر تا ۴ سال پس از انقضای بیمه‌نامه ادامه دارد.',
      'حق بیمه بر اساس طبقه ریسک تخصص تعیین می‌شود.',
    ],
    intake: 'SELF_SERVE',
    audience: 'INDIVIDUAL',
    icon: 'Stethoscope',
    order: 1,
    fields: [
      {
        name: 'specialty',
        label: 'تخصص',
        labelEn: 'Medical specialty',
        type: 'text',
        required: true,
        maxLength: 150,
        help: 'مثال: جراحی عمومی، زنان و زایمان، بیهوشی، دندان‌پزشکی، پرستاری',
        helpEn: 'e.g. general surgery, obstetrics, anaesthesia, dentistry, nursing',
      },
      {
        name: 'medicalCouncilNumber',
        label: 'شماره نظام پزشکی',
        labelEn: 'Medical council number',
        type: 'text',
        required: true,
        minLength: 3,
        maxLength: 20,
      },
      {
        name: 'practiceType',
        label: 'محل فعالیت',
        labelEn: 'Place of practice',
        type: 'select',
        required: true,
        options: [
          { value: 'private-office', label: 'مطب شخصی', labelEn: 'Private practice' },
          { value: 'hospital', label: 'بیمارستان', labelEn: 'Hospital' },
          { value: 'clinic', label: 'درمانگاه', labelEn: 'Clinic' },
          { value: 'both', label: 'مطب و بیمارستان', labelEn: 'Both practice and hospital' },
        ],
      },
      {
        name: 'yearsOfPractice',
        label: 'سابقه کار',
        labelEn: 'Years in practice',
        type: 'number',
        required: false,
        min: 0,
        max: 60,
        unit: 'سال',
        unitEn: 'years',
      },
      claimHistory({ help: 'اگر سابقه شکایت یا خسارت دارید شرح دهید.', helpEn: 'Describe any past complaints or claims.' }),
      {
        name: 'coverageLimit',
        label: 'سقف تعهدات مورد نیاز',
        labelEn: 'Coverage limit required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
    ],
  },

  {
    slug: 'liability-building-manager',
    categorySlug: 'liability',
    title: 'مسئولیت مدیران ساختمان',
    titleEn: 'Building manager liability',
    summary: 'پوشش حوادث مشاعات — پارکینگ، نما، تأسیسات',
    summaryEn: 'Covers accidents in common areas — parking, facade, plant',
    description:
      'این بیمه‌نامه مدیر ساختمان را در برابر ادعاهای ساکنان و اشخاص ثالث بابت حوادث مشاعات پوشش می‌دهد: آسیب خودروهای پارک‌شده، ریزش نما، حوادث کارکنان ساختمان و آتش‌سوزی در صورت احراز مسئولیت. بدون این بیمه‌نامه، مسئولیت مالی چنین حوادثی مستقیماً متوجه هیأت مدیره است. حوادث طبیعی مانند زلزله و سیل از پوشش خارج است.',
    descriptionEn:
      'This policy covers the building manager against claims by residents and third parties for accidents in the common parts: damage to parked cars, falling facade material, injury to building staff, and fire where liability is established. Without it, the financial responsibility for such incidents falls directly on the board. Natural disasters such as earthquake and flood are excluded.',
    coverages: [
      'آتش‌سوزی و انفجار (با احراز مسئولیت)',
      'خسارت خودروهای ساکنان در پارکینگ',
      'آسیب بدنی ناشی از ریزش نما',
      'آسیب بدنی کارکنان ساختمان',
    ],
    notes: ['حوادث طبیعی مانند زلزله و سیل مستثنی است.', 'افزایش دیه تنها یک بار اعمال می‌شود.'],
    intake: 'SELF_SERVE',
    audience: 'INDIVIDUAL',
    icon: 'Building',
    order: 2,
    fields: [
      area({ label: 'متراژ کل زیربنا', labelEn: 'Total floor area' }),
      unitCount(),
      {
        name: 'buildingUse',
        label: 'نوع کاربری ساختمان',
        labelEn: 'Building use',
        type: 'select',
        required: true,
        options: [
          { value: 'residential', label: 'مسکونی', labelEn: 'Residential' },
          { value: 'commercial', label: 'تجاری', labelEn: 'Commercial' },
          { value: 'mixed', label: 'مسکونی و تجاری', labelEn: 'Mixed use' },
          { value: 'office', label: 'اداری', labelEn: 'Office' },
        ],
      },
      {
        name: 'hasPoolOrSauna',
        label: 'ساختمان استخر یا سونا دارد',
        labelEn: 'Building has a pool or sauna',
        type: 'bool',
        help: 'وجود استخر یا سونا ریسک و در نتیجه حق بیمه را بالا می‌برد.',
        helpEn: 'A pool or sauna raises the assessed risk and the premium with it.',
      },
      {
        name: 'staffCount',
        label: 'تعداد کارکنان ساختمان',
        labelEn: 'Number of building staff',
        type: 'number',
        required: false,
        min: 0,
        max: 100,
        unit: 'نفر',
        unitEn: 'people',
      },
      {
        name: 'coverageLimit',
        label: 'سقف تعهدات مورد نیاز',
        labelEn: 'Coverage limit required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
    ],
  },

  {
    slug: 'liability-supervising-engineer',
    categorySlug: 'liability',
    title: 'مسئولیت حرفه‌ای مهندسین ناظر',
    titleEn: 'Supervising engineer professional liability',
    summary: 'پوشش قصور مهندس ناظر در پروژه ساختمانی',
    summaryEn: 'Covers a supervising engineer’s negligence on a build',
    description:
      'بیمه مسئولیت حرفه‌ای مهندسین ناظر، کارکنان اجرایی پروژه ساختمانی و اشخاص ثالث را در صورت بروز خسارت جانی یا مالی ناشی از سهل‌انگاری مهندس ناظر تحت پوشش قرار می‌دهد. پوشش‌های تکمیلی مانند افزایش خودکار نرخ دیه و پرداخت بدون رأی دادگاه قابل افزودن است. فرانشیز خسارت مالی ۱۰ درصد و فرانشیز خسارت بدنی صفر است.',
    descriptionEn:
      'This policy covers site personnel and third parties for bodily or property loss caused by the supervising engineer’s negligence on a construction project. Extensions such as automatic uplift of the blood-money rate and payment without a court ruling can be added. The deductible is 10% on property loss and nil on bodily injury.',
    coverages: ['غرامت فوت', 'غرامت نقص عضو', 'هزینه‌های پزشکی', 'خسارت‌های مالی'],
    optionalCoverages: [
      'افزایش خودکار نرخ دیه',
      'تعدد دیات',
      'جبران هزینه‌های اعتراض',
      'پرداخت بدون رأی دادگاه',
    ],
    notes: [
      'فرانشیز خسارت مالی ۱۰٪؛ فرانشیز خسارت بدنی صفر.',
      'اعلام خسارت حداکثر ظرف ۵ روز کاری.',
    ],
    intake: 'CALLBACK',
    audience: 'INDIVIDUAL',
    icon: 'Ruler',
    order: 3,
    fields: [
      {
        name: 'engineeringLicenceNumber',
        label: 'شماره پروانه نظام مهندسی',
        labelEn: 'Engineering council licence number',
        type: 'text',
        required: true,
        minLength: 3,
        maxLength: 30,
      },
      {
        name: 'discipline',
        label: 'رشته',
        labelEn: 'Discipline',
        type: 'select',
        required: true,
        options: [
          { value: 'civil', label: 'عمران', labelEn: 'Civil' },
          { value: 'architecture', label: 'معماری', labelEn: 'Architecture' },
          { value: 'mechanical', label: 'مکانیک', labelEn: 'Mechanical' },
          { value: 'electrical', label: 'برق', labelEn: 'Electrical' },
          { value: 'survey', label: 'نقشه‌برداری', labelEn: 'Surveying' },
        ],
      },
      {
        name: 'projectCount',
        label: 'تعداد پروژه‌های تحت نظارت',
        labelEn: 'Projects under supervision',
        type: 'number',
        required: true,
        min: 1,
        max: 200,
      },
      area({ label: 'مجموع متراژ پروژه‌ها', labelEn: 'Total area under supervision', required: false }),
      claimHistory(),
    ],
  },

  {
    slug: 'employer-liability-construction',
    categorySlug: 'liability',
    title: 'مسئولیت کارفرما در قبال کارکنان ساختمانی',
    titleEn: 'Employer liability — construction',
    summary: 'حوادث کارگاه ساختمانی — سقوط، ریزش، ماشین‌آلات',
    summaryEn: 'Construction site accidents — falls, collapse, machinery',
    description:
      'این بیمه‌نامه خسارت‌های جانی واردشده به کارگران در محدوده کارگاه ساختمانی و حین انجام کار را پوشش می‌دهد و هزینه‌های درمانی و غرامت نقص عضو یا فوت را جبران می‌کند. حوادث رایج مانند سقوط از ارتفاع، افتادن مصالح، خفگی در چاه و صدمات ماشین‌آلات تحت پوشش قرار می‌گیرد. قیمت‌گذاری بر مبنای فرم پیشنهاد و بررسی ریسک پروژه انجام می‌شود.',
    descriptionEn:
      'This policy covers bodily injury to workers within a construction site during the course of their work, paying treatment costs and compensation for dismemberment or death. Common site accidents — falls from height, falling materials, asphyxiation in shafts, machinery injuries — are covered. Pricing follows a proposal form and a risk review of the project.',
    coverages: [
      'حوادث سقوط از ارتفاع',
      'افتادن مصالح ساختمانی بر کارگران',
      'خفگی در چاه',
      'صدمات پی‌کنی و پایه‌ستون‌ها',
      'صدمات ناشی از بالابر، جرثقیل و ماشین‌آلات',
    ],
    notes: ['مهلت ثبت حادثه: ۵ روز از وقوع.'],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'HardHat',
    order: 4,
    fields: [
      {
        name: 'projectAddress',
        label: 'آدرس کارگاه',
        labelEn: 'Site address',
        type: 'textarea',
        required: true,
        maxLength: 400,
      },
      peopleCount({ label: 'تعداد کارگران', labelEn: 'Number of workers' }),
      area({ label: 'متراژ زیربنای پروژه', labelEn: 'Project floor area' }),
      {
        name: 'floorCount',
        label: 'تعداد طبقات',
        labelEn: 'Number of floors',
        type: 'number',
        required: true,
        min: 1,
        max: 100,
      },
      {
        name: 'projectMonths',
        label: 'مدت پروژه',
        labelEn: 'Project duration',
        type: 'number',
        required: true,
        min: 1,
        max: 120,
        unit: 'ماه',
        unitEn: 'months',
      },
      {
        name: 'coverageLimit',
        label: 'تعهدات درخواستی',
        labelEn: 'Limits required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
      claimHistory({ label: 'سوابق بیمه‌ای و خسارتی', labelEn: 'Insurance and claims history' }),
    ],
  },

  {
    slug: 'employer-liability-general',
    categorySlug: 'liability',
    title: 'مسئولیت کارفرما در قبال کارکنان (غیر ساختمانی)',
    titleEn: 'Employer liability — general',
    summary: 'کارگاه‌های خدماتی، بازرگانی و صنعتی',
    summaryEn: 'Service, commercial and industrial workplaces',
    description:
      'اگر حین انجام کار برای کارکنان حادثه‌ای رخ دهد و مسئولیت آن متوجه کارفرما باشد، جبران خسارت بر عهده اوست. این بیمه‌نامه آن مسئولیت را برای فعالیت‌های خدماتی، بازرگانی و صنعتی پوشش می‌دهد و شامل دیات، هزینه‌های پزشکی و مطالبات تبصره یک ماده ۶۶ قانون تأمین اجتماعی است. نکته مهم اینکه اسامی کارکنان باید پیش از وقوع خسارت به شرکت بیمه اعلام شده باشد.',
    descriptionEn:
      'If an employee is injured at work and the employer is liable, the employer pays. This policy covers that liability for service, commercial and industrial operations, including blood-money awards, medical costs and Social Security recovery claims. Critically, employee names must be filed with the insurer before any loss occurs.',
    coverages: [
      'فوت و نقص عضو در هر حادثه',
      'هزینه‌های پزشکی',
      'دیات و دیات غیرمسری',
      'مطالبات تبصره ۱ ماده ۶۶ قانون تأمین اجتماعی',
    ],
    optionalCoverages: [
      'جبران هزینه‌های پزشکی',
      'افزایش ریالی دیه تا یک سال',
      'مأموریت خارج از کارگاه',
    ],
    notes: [
      'ثبت اسامی کارکنان پیش از وقوع خسارت الزامی است.',
      'در فعالیت‌های پرریسک، بازدید از محل ضروری است.',
    ],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'Briefcase',
    order: 5,
    fields: [
      {
        name: 'activityType',
        label: 'نوع فعالیت',
        labelEn: 'Type of activity',
        type: 'select',
        required: true,
        options: [
          { value: 'service', label: 'خدماتی', labelEn: 'Service' },
          { value: 'commercial', label: 'بازرگانی', labelEn: 'Commercial' },
          { value: 'industrial', label: 'صنعتی', labelEn: 'Industrial' },
          { value: 'workshop', label: 'کارگاهی', labelEn: 'Workshop' },
        ],
      },
      {
        name: 'activityDescription',
        label: 'شرح فعالیت',
        labelEn: 'Description of the work',
        type: 'text',
        required: true,
        maxLength: 200,
      },
      peopleCount({ label: 'تعداد کارکنان', labelEn: 'Number of employees' }),
      {
        name: 'workplaceAddress',
        label: 'آدرس محل کار',
        labelEn: 'Workplace address',
        type: 'textarea',
        required: true,
        maxLength: 400,
      },
      {
        name: 'coverageLimit',
        label: 'تعهدات درخواستی',
        labelEn: 'Limits required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
      {
        name: 'optionalCovers',
        label: 'پوشش‌های فرعی مورد نظر',
        labelEn: 'Optional extensions wanted',
        type: 'multiselect',
        required: false,
        options: [
          { value: 'medical', label: 'جبران هزینه‌های پزشکی', labelEn: 'Medical expenses' },
          { value: 'diyeh-uplift', label: 'افزایش ریالی دیه تا یک سال', labelEn: 'Blood-money uplift for a year' },
          { value: 'off-site', label: 'مأموریت خارج از کارگاه', labelEn: 'Off-site assignments' },
        ],
      },
      claimHistory({ label: 'سوابق بیمه‌ای و خسارتی', labelEn: 'Insurance and claims history' }),
    ],
  },

  {
    slug: 'liability-other',
    categorySlug: 'liability',
    title: 'سایر بیمه‌های مسئولیت',
    titleEn: 'Other liability lines',
    summary: 'مسئولیت مشاغل و اصناف، تولیدکنندگان کالا و موارد خاص',
    summaryEn: 'Trade and professional liability, product liability, special cases',
    description:
      'بسیاری از مشاغل و اصناف مسئولیت‌هایی دارند که در بیمه‌نامه‌های استاندارد نمی‌گنجد — از مسئولیت تولیدکننده کالا تا مسئولیت مدیران فنی و مراکز آموزشی و ورزشی. این‌ها به صورت موردی و بر اساس شرح فعالیت قیمت‌گذاری می‌شوند. شرح دقیق فعالیت و ریسک‌های نگران‌کننده را بنویسید تا کارشناس بتواند بیمه‌نامه مناسب را پیشنهاد دهد.',
    descriptionEn:
      'Many trades carry liabilities that do not fit a standard policy — product liability for manufacturers, technical-director liability, liability for training centres and sports facilities. These are rated case by case against a description of the activity. Describe the work and the risks that worry you, and a specialist will propose the right cover.',
    coverages: ['مسئولیت مدنی در قبال اشخاص ثالث', 'مسئولیت حرفه‌ای', 'مسئولیت تولیدکننده کالا'],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'Scale',
    order: 6,
    fields: [
      {
        name: 'activityDescription',
        label: 'شرح فعالیت و مسئولیت مورد نظر',
        labelEn: 'Describe the activity and the liability',
        type: 'textarea',
        required: true,
        minLength: 20,
        maxLength: 1500,
        help: 'هرچه دقیق‌تر بنویسید، پیشنهاد کارشناس دقیق‌تر خواهد بود.',
        helpEn: 'The more specific you are, the better the proposal a specialist can make.',
      },
      currencyField('estimatedExposure', 'برآورد سقف ریسک', 'Estimated exposure', { required: false }),
      claimHistory(),
    ],
  },
];
