import type { ProductDef } from '../types.js';
import { area, claimHistory, currencyField, peopleCount, unitCount } from '../fields.js';

const LIABILITY_LIMITS = [
  {
    value: 'diyeh-1',
    label: 'یک دیه کامل',
    labelEn: 'One full blood-money unit',
  },
  { value: 'diyeh-2', label: 'دو دیه کامل', labelEn: 'Two full units' },
  { value: 'diyeh-3', label: 'سه دیه کامل', labelEn: 'Three full units' },
  {
    value: 'custom',
    label: 'سقف دلخواه — با کارشناس هماهنگ می‌شود',
    labelEn: 'Custom — agreed with a specialist',
  },
];

export const liabilityProducts: ProductDef[] = [
  {
    slug: 'liability-medical',
    categorySlug: 'liability',
    title: 'مسئولیت حرفه‌ای پزشکان و پیراپزشکان',
    titleEn: 'Medical professional liability',
    summary: 'پوشش قصور حرفه‌ای در ارائه خدمات درمانی',
    summaryEn: 'Covers professional negligence in delivering care',
    description:
      'بیمه مسئولیت پزشکان، پزشک را در برابر خسارت‌های مالی و جانی ناشی از قصور، خطا یا غفلت حرفه‌ای در جریان ارائه خدمات درمانی پوشش می‌دهد. حق بیمه به شدت به رشته تخصصی و سقف تعهدات انتخابی بستگی دارد، چون ریسک رشته‌های مختلف بسیار متفاوت است. تعهد بیمه‌گر تا چهار سال پس از پایان بیمه‌نامه نیز ادامه دارد.',
    descriptionEn:
      'Medical liability covers a clinician against financial and bodily-injury claims arising from professional negligence, error or omission while treating patients. The premium varies sharply by specialty and chosen limit, because risk differs enormously between disciplines. The insurer’s obligation extends four years beyond the policy’s expiry.',
    coverages: ['دیه فوت', 'دیه نقص عضو', 'هزینه‌های پزشکی بیمار'],
    notes: [
      'اعلام خسارت باید ظرف ۵ روز کاری انجام شود.',
      'تعهد بیمه‌گر تا ۴ سال پس از انقضای بیمه‌نامه ادامه دارد.',
      'حق بیمه بر اساس طبقه ریسک تخصص تعیین می‌شود.',
    ],
    exclusions: [
      'انجام درمان خارج از تخصص پزشک',
      'اقدامات پزشکی برخلاف ضوابط و مقررات',
      'مصرف مواد مخدر یا الکل توسط پزشک',
      'اعمال خارج از حدود مندرج در بیمه‌نامه',
      'خسارت‌های عمدی یا ناشی از تقلب',
    ],
    requiredDocuments: [
      'کارت ملی و مدارک هویتی',
      'پروانهٔ طبابت یا مجوز معتبر',
      'مدرک تخصص و شمارهٔ نظام پزشکی',
      'برای خسارت: احضاریه، رأی هیأت بدوی نظام پزشکی و در صورت فوت گواهی فوت و انحصار وراثت',
    ],
    premiumFactors: [
      'نوع تخصص و طبقه‌بندی شغلی',
      'حوزهٔ فعالیت',
      'سقف تعهدات انتخابی',
      'تخفیف عدم خسارت و نحوهٔ پرداخت',
    ],
    faq: [
      {
        question: 'اثر گذشته یعنی چه؟',
        answer:
          'تعهد بیمه‌گر به مدت اعتبار بیمه‌نامه محدود نمی‌شود. اگر حادثه در دورهٔ تحت پوشش رخ داده باشد، تعهد تا چهار سال پس از انقضای بیمه‌نامه ادامه دارد.',
      },
      {
        question: 'خرید این بیمه‌نامه اجباری است؟',
        answer: 'اجباری نیست و بیشتر به‌عنوان ابزار مدیریت ریسک حرفه‌ای استفاده می‌شود.',
      },
      {
        question: 'چه گروه‌هایی تحت پوشش قرار می‌گیرند؟',
        answer:
          'پزشکان عمومی، متخصصان و فوق‌تخصص‌ها، جراحان، دندان‌پزشکان و پرستاران و پیراپزشکان.',
      },
    ],
    keyFacts: [
      { label: 'اجباری بودن', value: 'اختیاری' },
      { label: 'اثر گذشته', value: 'تعهد بیمه‌گر تا چهار سال پس از انقضای بیمه‌نامه ادامه دارد' },
      { label: 'مبنای غرامت', value: 'رأی مراجع ذی‌صلاح، تا سقف تعهدات' },
      { label: 'گروه‌های تحت پوشش', value: 'پزشکان، جراحان، دندان‌پزشکان، پرستاران و پیراپزشکان' },
      { label: 'مدت بیمه‌نامه', value: 'یک‌ساله' },
    ],
    claimSteps: [
      'به‌محض دریافت احضاریه یا اخطاریه، شرکت بیمه را مطلع کنید.',
      'رأی هیأت بدوی نظام پزشکی را ضمیمهٔ پرونده کنید.',
      'پروانهٔ طبابت، مدرک تخصص و مدارک هویتی را ارائه دهید.',
      'در صورت فوت بیمار، گواهی فوت، تأییدیهٔ پزشکی قانونی و گواهی انحصار وراثت لازم است.',
    ],
    intake: 'SELF_SERVE',
    audience: 'INDIVIDUAL',
    icon: 'Stethoscope',
    order: 1,
    fields: [
      {
        name: 'specialty',
        label: 'تخصص',
        labelEn: 'Medical specialty',
        type: 'text',
        required: true,
        maxLength: 150,
        help: 'مثال: جراحی عمومی، زنان و زایمان، بیهوشی، دندان‌پزشکی، پرستاری',
        helpEn: 'e.g. general surgery, obstetrics, anaesthesia, dentistry, nursing',
      },
      {
        name: 'medicalCouncilNumber',
        label: 'شماره نظام پزشکی',
        labelEn: 'Medical council number',
        type: 'text',
        required: true,
        minLength: 3,
        maxLength: 20,
      },
      {
        name: 'practiceType',
        label: 'محل فعالیت',
        labelEn: 'Place of practice',
        type: 'select',
        required: true,
        options: [
          {
            value: 'private-office',
            label: 'مطب شخصی',
            labelEn: 'Private practice',
          },
          { value: 'hospital', label: 'بیمارستان', labelEn: 'Hospital' },
          { value: 'clinic', label: 'درمانگاه', labelEn: 'Clinic' },
          {
            value: 'both',
            label: 'مطب و بیمارستان',
            labelEn: 'Both practice and hospital',
          },
        ],
      },
      {
        name: 'yearsOfPractice',
        label: 'سابقه کار',
        labelEn: 'Years in practice',
        type: 'number',
        required: false,
        min: 0,
        max: 60,
        unit: 'سال',
        unitEn: 'years',
      },
      claimHistory({
        help: 'اگر سابقه شکایت یا خسارت دارید شرح دهید.',
        helpEn: 'Describe any past complaints or claims.',
      }),
      {
        name: 'coverageLimit',
        label: 'سقف تعهدات مورد نیاز',
        labelEn: 'Coverage limit required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
    ],
  },

  {
    slug: 'liability-building-manager',
    categorySlug: 'liability',
    title: 'مسئولیت مدیران ساختمان',
    titleEn: 'Building manager liability',
    summary: 'پوشش حوادث مشاعات — پارکینگ، نما، تأسیسات',
    summaryEn: 'Covers accidents in common areas — parking, facade, plant',
    description:
      'این بیمه‌نامه مدیر ساختمان را در برابر ادعاهای ساکنان و اشخاص ثالث بابت حوادث مشاعات پوشش می‌دهد: آسیب خودروهای پارک‌شده، ریزش نما، حوادث کارکنان ساختمان و آتش‌سوزی در صورت احراز مسئولیت. بدون این بیمه‌نامه، مسئولیت مالی چنین حوادثی مستقیماً متوجه هیأت مدیره است. حوادث طبیعی مانند زلزله و سیل از پوشش خارج است.',
    descriptionEn:
      'This policy covers the building manager against claims by residents and third parties for accidents in the common parts: damage to parked cars, falling facade material, injury to building staff, and fire where liability is established. Without it, the financial responsibility for such incidents falls directly on the board. Natural disasters such as earthquake and flood are excluded.',
    coverages: [
      'آتش‌سوزی و انفجار (با احراز مسئولیت)',
      'خسارت خودروهای ساکنان در پارکینگ',
      'آسیب بدنی ناشی از ریزش نما',
      'آسیب بدنی کارکنان ساختمان',
    ],
    notes: ['حوادث طبیعی مانند زلزله و سیل مستثنی است.', 'افزایش دیه تنها یک بار اعمال می‌شود.'],
    exclusions: [
      'حوادث و بلایای طبیعی مانند زلزله، سیل و طوفان',
      'سکه، پول، اوراق بهادار، اسناد و فلزات قیمتی',
      'خسارت‌های ناشی از نزاع و درگیری',
      'آتش‌سوزی یا انفجار ناشی از قصور مالکان یا ساکنان',
      'آسیب بدنی استفاده‌کنندگان آسانسور، در نبود سرویس منظم',
    ],
    requiredDocuments: [
      'گزارش کلانتری',
      'اسناد اورژانس و آمبولانس',
      'مدارک بیمارستان',
      'مستندات ارتباط کاری با فرد زیان‌دیده',
    ],
    premiumFactors: [
      'متراژ کل زیربنا شامل واحدها، راه‌پله و پارکینگ',
      'نوع کاربری ساختمان',
      'میزان تردد اشخاص ثالث در مشاعات',
      'ظرفیت پارکینگ',
      'وجود استخر یا سونا',
      'سقف تعهدات مالی و جانی و مدت بیمه‌نامه',
    ],
    faq: [
      {
        question: 'چرا مدیر ساختمان باید این بیمه‌نامه را تهیه کند؟',
        answer:
          'بر اساس مادهٔ ۱۴ قانون تملک آپارتمان‌ها، بیمه‌کردن ساختمان بر عهدهٔ مدیر است و او در برابر خسارت‌های ناشی از مشاعات مسئول است.',
      },
      {
        question: 'هزینه میان ساکنان چگونه تقسیم می‌شود؟',
        answer: 'معمولاً بر اساس مساحت اختصاصی هر واحد محاسبه و دریافت می‌شود.',
      },
      {
        question: 'ریزش نما همیشه پوشش دارد؟',
        answer: 'پرداخت خسارت ریزش نما معمولاً مشروط به آن است که عمر نما بیش از ۱۵ سال نباشد.',
      },
    ],
    keyFacts: [
      { label: 'مبنای قانونی', value: 'مادهٔ ۱۴ قانون تملک آپارتمان‌ها' },
      { label: 'خریدار بیمه‌نامه', value: 'مدیر ساختمان؛ هزینه میان واحدها تقسیم می‌شود' },
      { label: 'مبنای غرامت جانی', value: 'نرخ دیهٔ سال' },
      { label: 'شرط پوشش ریزش نما', value: 'عمر نما بیش از ۱۵ سال نباشد' },
      { label: 'بلایای طبیعی', value: 'پوشش داده نمی‌شود' },
    ],
    claimSteps: [
      'به فرد آسیب‌دیده رسیدگی و در صورت نیاز با اورژانس تماس بگیرید.',
      'گزارش کلانتری و مستندات اورژانس یا آمبولانس را تهیه کنید.',
      'حادثه را به شرکت بیمه اعلام و پرونده تشکیل دهید.',
      'مدارک بیمارستان و مستندات ارتباط با زیان‌دیده را ارائه دهید.',
    ],
    intake: 'SELF_SERVE',
    audience: 'INDIVIDUAL',
    icon: 'Building',
    order: 2,
    fields: [
      area({ label: 'متراژ کل زیربنا', labelEn: 'Total floor area' }),
      unitCount(),
      {
        name: 'buildingUse',
        label: 'نوع کاربری ساختمان',
        labelEn: 'Building use',
        type: 'select',
        required: true,
        options: [
          { value: 'residential', label: 'مسکونی', labelEn: 'Residential' },
          { value: 'commercial', label: 'تجاری', labelEn: 'Commercial' },
          { value: 'mixed', label: 'مسکونی و تجاری', labelEn: 'Mixed use' },
          { value: 'office', label: 'اداری', labelEn: 'Office' },
        ],
      },
      {
        name: 'hasPoolOrSauna',
        label: 'ساختمان استخر یا سونا دارد',
        labelEn: 'Building has a pool or sauna',
        type: 'bool',
        help: 'وجود استخر یا سونا ریسک و در نتیجه حق بیمه را بالا می‌برد.',
        helpEn: 'A pool or sauna raises the assessed risk and the premium with it.',
      },
      {
        name: 'staffCount',
        label: 'تعداد کارکنان ساختمان',
        labelEn: 'Number of building staff',
        type: 'number',
        required: false,
        min: 0,
        max: 100,
        unit: 'نفر',
        unitEn: 'people',
      },
      {
        name: 'coverageLimit',
        label: 'سقف تعهدات مورد نیاز',
        labelEn: 'Coverage limit required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
    ],
  },

  {
    slug: 'liability-supervising-engineer',
    categorySlug: 'liability',
    title: 'مسئولیت حرفه‌ای مهندسین ناظر',
    titleEn: 'Supervising engineer professional liability',
    summary: 'پوشش قصور مهندس ناظر در پروژه ساختمانی',
    summaryEn: 'Covers a supervising engineer’s negligence on a build',
    description:
      'بیمه مسئولیت حرفه‌ای مهندسین ناظر، کارکنان اجرایی پروژه ساختمانی و اشخاص ثالث را در صورت بروز خسارت جانی یا مالی ناشی از سهل‌انگاری مهندس ناظر تحت پوشش قرار می‌دهد. پوشش‌های تکمیلی مانند افزایش خودکار نرخ دیه و پرداخت بدون رأی دادگاه قابل افزودن است. فرانشیز خسارت مالی ۱۰ درصد و فرانشیز خسارت بدنی صفر است.',
    descriptionEn:
      'This policy covers site personnel and third parties for bodily or property loss caused by the supervising engineer’s negligence on a construction project. Extensions such as automatic uplift of the blood-money rate and payment without a court ruling can be added. The deductible is 10% on property loss and nil on bodily injury.',
    coverages: ['غرامت فوت', 'غرامت نقص عضو', 'هزینه‌های پزشکی', 'خسارت‌های مالی'],
    optionalCoverages: [
      'افزایش خودکار نرخ دیه',
      'تعدد دیات',
      'جبران هزینه‌های اعتراض',
      'پرداخت بدون رأی دادگاه',
    ],
    notes: [
      'فرانشیز خسارت مالی ۱۰٪؛ فرانشیز خسارت بدنی صفر.',
      'اعلام خسارت حداکثر ظرف ۵ روز کاری.',
    ],
    exclusions: [
      'تشعشعات رادیواکتیو و انفجار هسته‌ای',
      'جنگ، شورش و اقدامات تروریستی',
      'خسارت‌های عمدی',
      'حوادث طبیعی مانند زلزله، سیل و صاعقه',
      'خسارت‌های عدم‌النفع',
      'نداشتن پروانهٔ اشتغال معتبر در زمان حادثه',
    ],
    requiredDocuments: [
      'پروانهٔ اشتغال معتبر',
      'گزارش حادثه بر فرم سازمان تأمین اجتماعی',
      'مدارک شناسایی زیان‌دیده',
      'گزارش بازرس ادارهٔ کار',
      'گواهی پزشک معتمد دربارهٔ نوع حادثه و اتمام درمان',
      'برای فوت: گواهی فوت، جواز دفن و گواهی انحصار وراثت',
    ],
    premiumFactors: ['نوع و تعداد پوشش‌های انتخابی', 'میزان افزایش خودکار نرخ دیه', 'سقف تعهدات'],
    faq: [
      {
        question: 'فرانشیز دارد؟',
        answer: 'خسارت‌های بدنی فرانشیز ندارند؛ خسارت‌های مالی معمولاً ۱۰ درصد فرانشیز دارند.',
      },
      {
        question: 'مهلت اعلام خسارت چقدر است؟',
        answer: 'حداکثر پنج روز کاری از زمان وقوع حادثه.',
      },
    ],
    keyFacts: [
      { label: 'گروه‌های تحت پوشش', value: 'مهندسان ناظر، طراح، محاسب و مشاور' },
      { label: 'فرانشیز خسارت بدنی', value: 'ندارد' },
      { label: 'فرانشیز خسارت مالی', value: 'حدود ۱۰٪' },
      { label: 'مهلت اعلام خسارت', value: 'پنج روز کاری' },
      { label: 'شرط اصلی پوشش', value: 'داشتن پروانهٔ اشتغال معتبر در زمان حادثه' },
    ],
    claimSteps: [
      'حادثه را حداکثر ظرف پنج روز کاری به شعبهٔ شرکت بیمه اعلام کنید.',
      'فرم گزارش حادثهٔ سازمان تأمین اجتماعی را تکمیل کنید.',
      'گزارش بازرس ادارهٔ کار و مدارک شناسایی زیان‌دیده را ارائه دهید.',
      'گواهی پزشک معتمد دربارهٔ نوع حادثه و اتمام درمان را ضمیمه کنید.',
      'در صورت فوت، گواهی فوت، جواز دفن و گواهی انحصار وراثت لازم است.',
    ],
    intake: 'CALLBACK',
    audience: 'INDIVIDUAL',
    icon: 'Ruler',
    order: 3,
    fields: [
      {
        name: 'engineeringLicenceNumber',
        label: 'شماره پروانه نظام مهندسی',
        labelEn: 'Engineering council licence number',
        type: 'text',
        required: true,
        minLength: 3,
        maxLength: 30,
      },
      {
        name: 'discipline',
        label: 'رشته',
        labelEn: 'Discipline',
        type: 'select',
        required: true,
        options: [
          { value: 'civil', label: 'عمران', labelEn: 'Civil' },
          { value: 'architecture', label: 'معماری', labelEn: 'Architecture' },
          { value: 'mechanical', label: 'مکانیک', labelEn: 'Mechanical' },
          { value: 'electrical', label: 'برق', labelEn: 'Electrical' },
          { value: 'survey', label: 'نقشه‌برداری', labelEn: 'Surveying' },
        ],
      },
      {
        name: 'projectCount',
        label: 'تعداد پروژه‌های تحت نظارت',
        labelEn: 'Projects under supervision',
        type: 'number',
        required: true,
        min: 1,
        max: 200,
      },
      area({
        label: 'مجموع متراژ پروژه‌ها',
        labelEn: 'Total area under supervision',
        required: false,
      }),
      claimHistory(),
    ],
  },

  {
    slug: 'employer-liability-construction',
    categorySlug: 'liability',
    title: 'مسئولیت کارفرما در قبال کارکنان ساختمانی',
    titleEn: 'Employer liability — construction',
    summary: 'حوادث کارگاه ساختمانی — سقوط، ریزش، ماشین‌آلات',
    summaryEn: 'Construction site accidents — falls, collapse, machinery',
    description:
      'این بیمه‌نامه خسارت‌های جانی واردشده به کارگران در محدوده کارگاه ساختمانی و حین انجام کار را پوشش می‌دهد و هزینه‌های درمانی و غرامت نقص عضو یا فوت را جبران می‌کند. حوادث رایج مانند سقوط از ارتفاع، افتادن مصالح، خفگی در چاه و صدمات ماشین‌آلات تحت پوشش قرار می‌گیرد. قیمت‌گذاری بر مبنای فرم پیشنهاد و بررسی ریسک پروژه انجام می‌شود.',
    descriptionEn:
      'This policy covers bodily injury to workers within a construction site during the course of their work, paying treatment costs and compensation for dismemberment or death. Common site accidents — falls from height, falling materials, asphyxiation in shafts, machinery injuries — are covered. Pricing follows a proposal form and a risk review of the project.',
    coverages: [
      'حوادث سقوط از ارتفاع',
      'افتادن مصالح ساختمانی بر کارگران',
      'خفگی در چاه',
      'صدمات پی‌کنی و پایه‌ستون‌ها',
      'صدمات ناشی از بالابر، جرثقیل و ماشین‌آلات',
    ],
    notes: ['مهلت ثبت حادثه: ۵ روز از وقوع.'],
    exclusions: [
      'امراض طولانی‌مدت ناشی از فعالیت عادی',
      'حوادث وسایل نقلیهٔ موتوری مشمول بیمهٔ اجباری',
      'تشعشعات مواد رادیواکتیو',
      'جنگ، اعتصاب، اغتشاش و اعمال تروریستی',
      'حوادث طبیعی مانند زلزله، سیل، طوفان و صاعقه',
      'خسارت ناشی از عمد یا تقلب بیمه‌گذار',
      'حوادث ناشی از درگیری و نزاع',
      'خسارات ناشی از مسکرات و مواد مخدر',
      'خسارت واردشده به کارکنان کمتر از ۱۵ سال',
    ],
    requiredDocuments: [
      'فرم اعلام حادثه، ظرف پنج روز از وقوع',
      'مدارک شناسایی فرد مصدوم',
      'قرارداد کارگر و کارفرما',
      'فهرست بیمهٔ تأمین اجتماعی',
      'پروانهٔ ساخت',
      'مدارک درمانی و صورتحساب بیمارستان',
    ],
    premiumFactors: [
      'تعداد و نوع پوشش‌های انتخابی',
      'سقف تعهدات',
      'تعداد کارکنان',
      'نوع و مرحلهٔ عملیات ساختمانی',
    ],
    keyFacts: [
      { label: 'محدودهٔ پوشش', value: 'محوطهٔ کارگاه و حین انجام کار' },
      { label: 'مهلت اعلام حادثه', value: 'پنج روز' },
      { label: 'حداقل سن کارکنان', value: '۱۵ سال' },
      { label: 'مبنای غرامت', value: 'نرخ دیهٔ سال و رأی مراجع ذی‌صلاح' },
      { label: 'بلایای طبیعی', value: 'پوشش داده نمی‌شود' },
    ],
    claimSteps: [
      'به مصدوم رسیدگی و حادثه را به مراجع ذی‌صلاح گزارش کنید.',
      'فرم اعلام حادثه را ظرف پنج روز به شرکت بیمه تحویل دهید.',
      'قرارداد کارگر و کارفرما و فهرست بیمهٔ تأمین اجتماعی را ارائه دهید.',
      'پروانهٔ ساخت و مدارک شناسایی مصدوم را ضمیمه کنید.',
      'مدارک درمانی و صورتحساب بیمارستان را برای تسویه ارائه دهید.',
    ],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'HardHat',
    order: 4,
    fields: [
      {
        name: 'projectAddress',
        label: 'آدرس کارگاه',
        labelEn: 'Site address',
        type: 'textarea',
        required: true,
        maxLength: 400,
      },
      peopleCount({ label: 'تعداد کارگران', labelEn: 'Number of workers' }),
      area({ label: 'متراژ زیربنای پروژه', labelEn: 'Project floor area' }),
      {
        name: 'floorCount',
        label: 'تعداد طبقات',
        labelEn: 'Number of floors',
        type: 'number',
        required: true,
        min: 1,
        max: 100,
      },
      {
        name: 'projectMonths',
        label: 'مدت پروژه',
        labelEn: 'Project duration',
        type: 'number',
        required: true,
        min: 1,
        max: 120,
        unit: 'ماه',
        unitEn: 'months',
      },
      {
        name: 'coverageLimit',
        label: 'تعهدات درخواستی',
        labelEn: 'Limits required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
      claimHistory({
        label: 'سوابق بیمه‌ای و خسارتی',
        labelEn: 'Insurance and claims history',
      }),
    ],
  },

  {
    slug: 'employer-liability-general',
    categorySlug: 'liability',
    title: 'مسئولیت کارفرما در قبال کارکنان (غیر ساختمانی)',
    titleEn: 'Employer liability — general',
    summary: 'کارگاه‌های خدماتی، بازرگانی و صنعتی',
    summaryEn: 'Service, commercial and industrial workplaces',
    description:
      'اگر حین انجام کار برای کارکنان حادثه‌ای رخ دهد و مسئولیت آن متوجه کارفرما باشد، جبران خسارت بر عهده اوست. این بیمه‌نامه آن مسئولیت را برای فعالیت‌های خدماتی، بازرگانی و صنعتی پوشش می‌دهد و شامل دیات، هزینه‌های پزشکی و مطالبات تبصره یک ماده ۶۶ قانون تأمین اجتماعی است. نکته مهم اینکه اسامی کارکنان باید پیش از وقوع خسارت به شرکت بیمه اعلام شده باشد.',
    descriptionEn:
      'If an employee is injured at work and the employer is liable, the employer pays. This policy covers that liability for service, commercial and industrial operations, including blood-money awards, medical costs and Social Security recovery claims. Critically, employee names must be filed with the insurer before any loss occurs.',
    coverages: [
      'فوت و نقص عضو در هر حادثه',
      'هزینه‌های پزشکی',
      'دیات و دیات غیرمسری',
      'مطالبات تبصره ۱ ماده ۶۶ قانون تأمین اجتماعی',
    ],
    optionalCoverages: [
      'جبران هزینه‌های پزشکی',
      'افزایش ریالی دیه تا یک سال',
      'مأموریت خارج از کارگاه',
    ],
    notes: [
      'ثبت اسامی کارکنان پیش از وقوع خسارت الزامی است.',
      'در فعالیت‌های پرریسک، بازدید از محل ضروری است.',
    ],
    exclusions: [
      'انفجار و مواد آتش‌زا، بدون توافق قبلی',
      'بیماری‌های شغلی مزمن',
      'تشعشعات رادیواکتیو و انفجار هسته‌ای',
      'جنگ، اعتصاب و تروریسم',
      'حوادث طبیعی مانند زلزله، سیل و طوفان',
      'خسارات ناشی از مصرف مسکرات',
      'خسارت واردشده به کارکنان کمتر از ۱۵ سال',
    ],
    requiredDocuments: [
      'فهرست اسامی کارکنان، پیش از وقوع حادثه',
      'قرارداد کار و فهرست بیمهٔ تأمین اجتماعی',
      'مدارک درمانی و گزارش حادثه',
    ],
    premiumFactors: ['ریسک شغلی و نوع فعالیت', 'سقف پوشش‌ها', 'تعداد کارکنان تحت پوشش'],
    faq: [
      {
        question: 'چرا اسامی کارکنان باید از قبل اعلام شود؟',
        answer:
          'پوشش تنها برای کارکنانی برقرار است که پیش از وقوع خسارت به شرکت بیمه معرفی شده‌اند.',
      },
      {
        question: 'چرا نرخ فوراً اعلام نمی‌شود؟',
        answer:
          'در فعالیت‌های پرریسک و پروژه‌های عمرانی نرخ پس از بازدید محل کار و به‌صورت جداگانه تعیین می‌شود.',
      },
    ],
    keyFacts: [
      { label: 'شرط فعال بودن پوشش', value: 'اعلام اسامی کارکنان پیش از وقوع خسارت' },
      { label: 'حداقل سن کارکنان', value: '۱۵ سال' },
      { label: 'تعیین نرخ', value: 'پس از بازدید محل کار در فعالیت‌های پرریسک' },
      { label: 'بیماری‌های شغلی مزمن', value: 'پوشش داده نمی‌شود' },
    ],
    claimSteps: [
      'حادثه را به شرکت بیمه اعلام و فرم اعلام حادثه را تکمیل کنید.',
      'قرارداد کار و فهرست بیمهٔ تأمین اجتماعی کارکنان را ارائه دهید.',
      'گزارش حادثه و مدارک شناسایی مصدوم را ضمیمه کنید.',
      'مدارک درمانی و صورتحساب‌ها را برای جبران هزینه تحویل دهید.',
    ],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'Briefcase',
    order: 5,
    fields: [
      {
        name: 'activityType',
        label: 'نوع فعالیت',
        labelEn: 'Type of activity',
        type: 'select',
        required: true,
        options: [
          { value: 'service', label: 'خدماتی', labelEn: 'Service' },
          { value: 'commercial', label: 'بازرگانی', labelEn: 'Commercial' },
          { value: 'industrial', label: 'صنعتی', labelEn: 'Industrial' },
          { value: 'workshop', label: 'کارگاهی', labelEn: 'Workshop' },
        ],
      },
      {
        name: 'activityDescription',
        label: 'شرح فعالیت',
        labelEn: 'Description of the work',
        type: 'text',
        required: true,
        maxLength: 200,
      },
      peopleCount({ label: 'تعداد کارکنان', labelEn: 'Number of employees' }),
      {
        name: 'workplaceAddress',
        label: 'آدرس محل کار',
        labelEn: 'Workplace address',
        type: 'textarea',
        required: true,
        maxLength: 400,
      },
      {
        name: 'coverageLimit',
        label: 'تعهدات درخواستی',
        labelEn: 'Limits required',
        type: 'select',
        required: true,
        options: LIABILITY_LIMITS,
      },
      {
        name: 'optionalCovers',
        label: 'پوشش‌های فرعی مورد نظر',
        labelEn: 'Optional extensions wanted',
        type: 'multiselect',
        required: false,
        options: [
          {
            value: 'medical',
            label: 'جبران هزینه‌های پزشکی',
            labelEn: 'Medical expenses',
          },
          {
            value: 'diyeh-uplift',
            label: 'افزایش ریالی دیه تا یک سال',
            labelEn: 'Blood-money uplift for a year',
          },
          {
            value: 'off-site',
            label: 'مأموریت خارج از کارگاه',
            labelEn: 'Off-site assignments',
          },
        ],
      },
      claimHistory({
        label: 'سوابق بیمه‌ای و خسارتی',
        labelEn: 'Insurance and claims history',
      }),
    ],
  },

  {
    slug: 'liability-other',
    categorySlug: 'liability',
    title: 'سایر بیمه‌های مسئولیت',
    titleEn: 'Other liability lines',
    summary: 'مسئولیت مشاغل و اصناف، تولیدکنندگان کالا و موارد خاص',
    summaryEn: 'Trade and professional liability, product liability, special cases',
    description:
      'بسیاری از مشاغل و اصناف مسئولیت‌هایی دارند که در بیمه‌نامه‌های استاندارد نمی‌گنجد — از مسئولیت تولیدکننده کالا تا مسئولیت مدیران فنی و مراکز آموزشی و ورزشی. این‌ها به صورت موردی و بر اساس شرح فعالیت قیمت‌گذاری می‌شوند. شرح دقیق فعالیت و ریسک‌های نگران‌کننده را بنویسید تا کارشناس بتواند بیمه‌نامه مناسب را پیشنهاد دهد.',
    descriptionEn:
      'Many trades carry liabilities that do not fit a standard policy — product liability for manufacturers, technical-director liability, liability for training centres and sports facilities. These are rated case by case against a description of the activity. Describe the work and the risks that worry you, and a specialist will propose the right cover.',
    coverages: ['مسئولیت مدنی در قبال اشخاص ثالث', 'مسئولیت حرفه‌ای', 'مسئولیت تولیدکننده کالا'],
    intake: 'CALLBACK',
    audience: 'CORPORATE',
    icon: 'Scale',
    order: 6,
    fields: [
      {
        name: 'activityDescription',
        label: 'شرح فعالیت و مسئولیت مورد نظر',
        labelEn: 'Describe the activity and the liability',
        type: 'textarea',
        required: true,
        minLength: 20,
        maxLength: 1500,
        help: 'هرچه دقیق‌تر بنویسید، پیشنهاد کارشناس دقیق‌تر خواهد بود.',
        helpEn: 'The more specific you are, the better the proposal a specialist can make.',
      },
      currencyField('estimatedExposure', 'برآورد سقف ریسک', 'Estimated exposure', {
        required: false,
      }),
      claimHistory(),
    ],
  },
];
