import { createReadStream } from 'node:fs';
import { mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Readable } from 'node:stream';
import { env } from '../../config/env.js';
import { logger } from '../../config/logger.js';
import { AppError } from '../../middleware/errorHandler.js';
import { EMPTY_PAYLOAD_HASH, sha256Hex, signRequest } from './sigv4.js';

/**
 * Where uploaded files actually live.
 *
 * Two drivers behind one interface. The local one writes to a directory, which
 * is right for a laptop and for a single-container deployment with a mounted
 * volume. The S3 one talks to any S3-compatible endpoint — ArvanCloud, MinIO,
 * Backblaze, AWS — which is what a second API container needs, since two
 * containers cannot share a container filesystem.
 *
 * This split is not speculative architecture. Before it, `UPLOAD_DIR` pointed
 * inside the container with no volume behind it, so every deploy destroyed
 * every attachment and every CV that had been uploaded since the last one.
 */

export interface StoredObject {
  sizeBytes: number;
  stream: Readable;
}

export interface StorageDriver {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  /** Throws AppError 410 when the object is not there — it is gone, not absent. */
  get(key: string): Promise<StoredObject>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by us, but never trust one that came back from a database. */
function assertSafeKey(key: string): void {
  if (key !== path.basename(key) || key === '.' || key === '..' || key.includes('\\')) {
    throw new AppError('مسیر فایل نامعتبر است.', 400);
  }
}

// ---------------------------------------------------------------------------
// Local disk
// ---------------------------------------------------------------------------

class LocalDiskDriver implements StorageDriver {
  readonly name = 'local';

  private root(): string {
    return path.resolve(env.UPLOAD_DIR);
  }

  private pathFor(key: string): string {
    assertSafeKey(key);
    return path.join(this.root(), key);
  }

  async put(key: string, body: Buffer): Promise<void> {
    await mkdir(this.root(), { recursive: true });
    // 0o640: readable by the app user and its group, by nobody else. These are
    // client documents, frequently under NDA.
    await writeFile(this.pathFor(key), body, { mode: 0o640 });
  }

  async get(key: string): Promise<StoredObject> {
    const full = this.pathFor(key);
    const stats = await stat(full).catch(() => null);
    if (!stats) throw new AppError('فایل روی سرور موجود نیست.', 410);
    return { sizeBytes: stats.size, stream: createReadStream(full) };
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch {
      // Already gone is the desired state.
    }
  }
}

// ---------------------------------------------------------------------------
// S3-compatible
// ---------------------------------------------------------------------------

class S3Driver implements StorageDriver {
  readonly name = 's3';

  constructor(
    private readonly endpoint: string,
    private readonly bucket: string,
    private readonly region: string,
    private readonly accessKeyId: string,
    private readonly secretAccessKey: string,
    /** Path style (endpoint/bucket/key) is what most non-AWS providers want. */
    private readonly forcePathStyle: boolean,
  ) {}

  private target(key: string): { url: URL; host: string; path: string } {
    assertSafeKey(key);
    const base = new URL(this.endpoint);
    if (this.forcePathStyle) {
      const p = `/${this.bucket}/${encodeURIComponent(key)}`;
      return { url: new URL(p, base), host: base.host, path: p };
    }
    const host = `${this.bucket}.${base.host}`;
    const p = `/${encodeURIComponent(key)}`;
    return { url: new URL(`${base.protocol}//${host}${p}`), host, path: p };
  }

  private async send(
    method: string,
    key: string,
    body?: Buffer,
    contentType?: string,
  ): Promise<Response> {
    const { url, host, path: signedPath } = this.target(key);

    const headers = signRequest({
      method,
      path: signedPath,
      host,
      region: this.region,
      service: 's3',
      accessKeyId: this.accessKeyId,
      secretAccessKey: this.secretAccessKey,
      payloadHash: body ? sha256Hex(body) : EMPTY_PAYLOAD_HASH,
      headers: contentType ? { 'content-type': contentType } : undefined,
    });

    return fetch(url, {
      method,
      headers,
      body,
      // Uploads are capped at 10 MB, so a minute is generous even on a bad link.
      signal: AbortSignal.timeout(60_000),
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const response = await this.send('PUT', key, body, contentType);
    if (!response.ok) {
      const detail = await response.text().catch(() => '');
      logger.error({ key, status: response.status, detail: detail.slice(0, 300) }, 'S3 put failed');
      throw new AppError('ذخیرهٔ فایل ناموفق بود.', 502);
    }
  }

  async get(key: string): Promise<StoredObject> {
    const response = await this.send('GET', key);
    if (response.status === 404) throw new AppError('فایل روی سرور موجود نیست.', 410);
    if (!response.ok || !response.body) {
      logger.error({ key, status: response.status }, 'S3 get failed');
      throw new AppError('دریافت فایل ناموفق بود.', 502);
    }
    return {
      sizeBytes: Number(response.headers.get('content-length') ?? 0),
      stream: Readable.fromWeb(response.body as Parameters<typeof Readable.fromWeb>[0]),
    };
  }

  async delete(key: string): Promise<void> {
    const response = await this.send('DELETE', key);
    // 204 is success and 404 means it is already in the state we want.
    if (!response.ok && response.status !== 404) {
      logger.error({ key, status: response.status }, 'S3 delete failed');
    }
  }
}

// ---------------------------------------------------------------------------

function build(): StorageDriver {
  const name = env.STORAGE_DRIVER.toLowerCase();

  if (name === 'local') {
    if (env.isProduction && !env.STORAGE_ALLOW_LOCAL_IN_PRODUCTION) {
      // A container filesystem is not storage. Refusing here is what stops the
      // original defect — files silently destroyed on each deploy — recurring
      // because someone forgot to set the driver. Setting the escape hatch is
      // a promise that UPLOAD_DIR is a mounted, backed-up volume.
      throw new Error(
        'FATAL: STORAGE_DRIVER=local in production. Either set STORAGE_DRIVER=s3, or set ' +
          'STORAGE_ALLOW_LOCAL_IN_PRODUCTION=true to confirm UPLOAD_DIR is a durable, backed-up volume.',
      );
    }
    return new LocalDiskDriver();
  }

  if (name === 's3') {
    const missing = (['STORAGE_ENDPOINT', 'STORAGE_BUCKET', 'STORAGE_ACCESS_KEY', 'STORAGE_SECRET_KEY'] as const)
      .filter((k) => !env[k]);
    if (missing.length > 0) {
      throw new Error(`STORAGE_DRIVER=s3 requires ${missing.join(', ')}`);
    }
    return new S3Driver(
      env.STORAGE_ENDPOINT,
      env.STORAGE_BUCKET,
      env.STORAGE_REGION,
      env.STORAGE_ACCESS_KEY,
      env.STORAGE_SECRET_KEY,
      env.STORAGE_FORCE_PATH_STYLE,
    );
  }

  throw new Error(`Unknown STORAGE_DRIVER "${env.STORAGE_DRIVER}" (expected: local, s3)`);
}

let driver: StorageDriver | undefined;

/** Lazily built so importing this module never throws at load time. */
export function storage(): StorageDriver {
  driver ??= build();
  return driver;
}
